#ifndef NOVAWEB_HEADER_H
#define NOVAWEB_HEADER_H

#define HTTP_VERSION "1.1"
#define MAX_METHOD_LENGTH 10
#define MAX_URI_LENGTH 1024
#define MAX_VERSION_LENGTH 20
#define MAX_HEADER_COUNT 20
#define MAX_HEADER_NAME_LENGTH 50
#define MAX_HEADER_VALUE_LENGTH 150
#define MAX_BODY_LENGTH 4096
#define MAX_RESPONSE_LENGTH (MAX_BODY_LENGTH + MAX_HEADER_COUNT * (MAX_HEADER_NAME_LENGTH + MAX_HEADER_VALUE_LENGTH) + 100)
#define KEEP_ALIVE_TIMEOUT_SECONDS 5
#define KEEP_ALIVE_MAX_REQUESTS 100
#define MAX_KEEP_ALIVE_LENGTH 30

typedef struct {
    char name[MAX_HEADER_NAME_LENGTH];
    char value[MAX_HEADER_VALUE_LENGTH];
} http_header;

#endif //NOVAWEB_HEADER_H
